kind: Service
apiVersion: v1
metadata:
  name: nginx 
spec:
  selector:
    svc: nginx
  ports:
  - protocol: TCP
    port: 80
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      svc: nginx
  replicas: 1
  template:
    metadata:
      labels:
        svc: nginx
    spec:
      containers:
      - name: nginx
        image: sotadb/nginx 
        ports: 
        - containerPort: 80
